import Footer from "../_components/Footer";

export const metadata = {
  title: "Subscription",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
